name: Backend Deploy 
 
on:
  push:
    branches: [main]
    paths:
     - 'Backend/Terraform/**'
     - 'Backend/**/*.py'
     - 'Backend/**/*.zip'
     - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_bucket_name: ${{ vars.TF_VAR_BUCKET_NAME }}
        TF_VAR_region: ${{ vars.TF_VAR_REGION }}
        TF_VAR_frontend_directory: ${{ vars.TF_VAR_FRONTEND_DIRECTORY }}
        TF_VAR_domain_name: ${{ vars.TF_VAR_DOMAIN_NAME }}
        TF_VAR_zone_id: ${{ vars.TF_VAR_ZONE_ID }}
        TF_VAR_index_document: ${{ vars.TF_VAR_INDEX_DOCUMENT }}
        TF_VAR_error_document: ${{ vars.TF_VAR_ERROR_DOCUMENT }}
        TF_VAR_frontend_path: ${{ vars.TF_VAR_FRONTEND_PATH }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: Backend/Terraform
     

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: Backend/Terraform

      - name: Debug Env Vars
        run: |
          echo "Region: $TF_VAR_region"

      - name: Terraform Plan
        run: terraform plan
        working-directory: Backend/Terraform
        timeout-minutes: 5

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Backend/Terraform


      - name: Terraform Destroy
        if: always()  # This ensures it runs even if previous steps fail
        run: terraform destroy -auto-approve
        working-directory: Backend/Terraform